//
// Created by Ilir on 2021-12-13.
//

#ifndef PROJECTMCODES_CROWDCONTROL_H
#define PROJECTMCODES_CROWDCONTROL_H


#include "Assembly.h"
#include "Debug.h"
#include "Wii/EXI/EXI.h"
#include "Memory.h"
#include "Wii/PAD/PADStatus.h"
#include "Brawl/GF/GameFrame.h"
#include "Brawl/FT/Fighter.h"
#include <Brawl/FT/ftManager.h>
#include "MenuPages.h"

enum CCEffect
{
    EFFECT_NOT_CONNECTED = 0,
    EFFECT_NONE = 1,
    EFFECT_UNKNOWN = 2,
    EFFECT_GIVE_DAMAGE = 3,
    EFFECT_GIVE_STOCKS = 4,
    EFFECT_GIVE_TIME = 5,
    EFFECT_ITEM_SPAWN_REGULAR = 6,
    EFFECT_ITEM_SPAWN_POKEMON = 7,
    EFFECT_ITEM_SPAWN_ASSIST = 8,
    EFFECT_ITEM_ATTACH_GOOEY = 9,
    EFFECT_STATUS_METAL = 10,
    EFFECT_STATUS_CURRY = 11,
    EFFECT_STATUS_HAMMER = 12,
    EFFECT_STATUS_SUPERSTAR = 13,
    EFFECT_STATUS_FLOWER = 14,
    EFFECT_STATUS_HEART = 15,
    EFFECT_STATUS_SLOW = 16,
    EFFECT_STATUS_MUSHROOM = 17,
    EFFECT_STATUS_EQUIP = 18,
    EFFECT_STATUS_SWAP = 19,
    EFFECT_STATUS_FINALSMASH = 20,
    EFFECT_STATUS_ACTION = 21,
    EFFECT_WARP_TOPLAYER = 22,
    EFFECT_WARP_SWAP = 23,
    EFFECT_MODE_FLIGHT = 24,
    EFFECT_MODE_BORDERLESS = 25,
    EFFECT_MODE_ELEMENT = 26,
    EFFECT_MODE_ZTD = 27,
    EFFECT_MODE_BOMBRAIN = 28,
    EFFECT_MODE_WILD = 29,
    EFFECT_MODE_SPEED = 30,
    EFFECT_MODE_WAR = 31,
    EFFECT_MODE_RANDOMANGLE = 32,
    EFFECT_MODE_BIGHEAD = 33,
    EFFECT_MODE_HITFALL = 34,
    EFFECT_MODE_LANDINGLAG = 35,
};

//hacky way to check if in game
enum SCENE_TYPE {
    SCENE_MAIN_MENU = 0x1,
    SCENE_HRC_CSS = 0x2,
    SCENE_DIFFICULTY_TRAINING_CSS = 0x4,
    SCENE_CSS_HRC = 0x5,
    SCENE_DIFFICULTY_TRAINING_SSS_EVT_CSS = 0x6,
    SCENE_SSS_BTT = 0x7,
    SCENE_TRAINING_MODE_MMS = 0x8,
    SCENE_VS = 0xA
};


#endif //PROJECTMCODES_CROWDCONTROL_H
